# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d59bdd97bf133492be1980e3c182d8b9fc37fee8b3542559cdc7268cf8f1c6744bd731a4ff54da1b6e0491305151c9c9600525bb839b764008695dcd88e113

test:
  secret_key_base: 7e706061957246e24255c8a2e9df91a8356a8229c1ce79fbf2909e2473c0837cdefd92454ba72ad85cc5b86a1029c53eb73f3ff29555d1b1fd6b6721b54fdda2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
